name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --legacy-peer-deps
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run build:doc
      - uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
