name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci --legacy-peer-deps
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: module
          path: dist
      - uses: actions/upload-artifact@v2
        with:
          name: doc
          path: doc

  deploy-module:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'release'
      - uses: actions/download-artifact@v2
        with:
          name: module
          path: dist
      - run: |
          git config --local user.email "_"
          git config --local user.name "Github Actions"
          git fetch origin master
          git checkout origin/master -- package.json
          git add dist package.json
          git commit -m "Update build artifacts"
          git push origin release

  deploy-doc:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: doc
          path: doc
      - uses: peaceiris/actions-gh-pages@v3.9.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
